import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getServerSession } from "next-auth";
import Logout from "./(components)/Logout";
import { NextAuthProvider } from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <nav>
            {!!session && <Logout />}
            {!session && <Link href="/login">Login</Link>}
          </nav>
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
